version: '3'

services:
    postgres:
        image: postgres
        container_name: financeapp-postgres
        environment:
            POSTGRES_PASSWORD: csc
            POSTGRES_USER: root
            POSTGRES_DB: finance-app
        ports:
            - '5432:5432'
        volumes:
            - ./.postgres-data:/var/lib/postgres/data
