name: Deploy

on:
    push:
        branches:
            - main

jobs:
    check:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Install dependencies
              run: npm install

            - name: Create .env.test file
              run: |
                  echo "DATABASE_URL=postgresql://root:csc@localhost:5433/finance-app" >> .env.test

            - name: Install dependencies
              run: npm ci

            - name: Run ESLint
              run: npm run eslint:check

            - name: Run Prettier
              run: npm run prettier:check

            - name: Run Tests
              run: npm run test

    migrate:
        runs-on: ubuntu-latest
        needs: check
        environment: production
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Install dependencies
              run: npm install

            - name: Make envfile
              uses: SpicyPizza/create-envfile@v2.0
              with:
                  envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}

            - name: Run migrations
              run: npx prisma migrate deploy
    deploy:
        runs-on: ubuntu-latest
        needs: migrate
        environment: production

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Deploy to Production
              run: |
                  curl "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
