name: Deploy

on:
    push:
        branches:
            - main

jobs:
    check:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Install dependencies
              run: npm ci

            - name: Run ESLint
              run: npm run eslint:check

            - name: Run Prettier
              run: npm run prettier:check

            - name: Run Tests
              run: npm run test
